server:
  port: 9784
#  servlet:
#    session:
#      timeout: 1m # 设置session有效时间为 1分钟，最低也是1分钟，如果设置的小于1分钟就按一分钟处理。
#      cookie:
#        name: JSESSIONID # 指定浏览器Cookie中关于SessionID保存的那个名称

spring:
  # 数据源配置
  datasource:
    username: root
    password: mallmysql
    url: jdbc:mysql://www.it307.top/security-oauth2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  redis:
    host: www.it307.top
    port: 6379
    password: mcp2RliHg
    lettuce:
      shutdown-timeout: 5000 # 超时时间