server:
  port: 8082

socketIo:
  host: 192.168.124.7 # 前段链接地址(一定是当前计算机的地址，否则会报java.net.BindException: Cannot assign requested address: bind)
  port: 9092 # 端口号
  bossCount: 1 # socket连接数大小（如只监听一个端口boss线程组为1即可）
  workCount: 100
  allowCustomRequests: true
  maxFramePayloadLength: 1048576 # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxHttpContentLength: 1048576 # 设置http交互最大内容长度
  pingInterval: 25000 # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingTimeout: 6000000 # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  upgradeTimeout: 1000000 # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
