server:
  port: 8401

spring:
  application:
    name: sentinel-service # 当前工程名称
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080 # sentinel地址
        port: 8719  # Sentinel api端口 ,默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource: # 将sentinel持久化到nacos中
        dsl:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data_type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*' # springboot 监控 Actuator 的端点暴露，* 为暴露所有端点。